### ISSUE TITLE
Crawl picture scripts

### ISSUE THREAD

**Issue by Founder001** [Founder001/Python#1]
Can be downloaded to the local E:/test file to implement a picture to watermark

**Comment by djyuning** [comment]
我也想知道~！ @Founder001

**Comment by Founder001** [comment]
I'm waiting for a friend to answer @djyuning

**Comment by djyuning** [comment]
@Founder001 Hi, I recommend you understand  OpenCV（Open Source Computer Vision Library）. [python利用opencv去除水印方法](https://www.cnblogs.com/lgh344902118/p/7928054.html)

**Comment by Founder001** [comment]
Thanks
